name: Test all days
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=7168
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CROSS_REPO_TOKEN }}
      - name: Install packages
        run: yarn install
      - name: Run Tests
        run: yarn test
